language: java
deploy:
  provider: heroku
  api_key:
    secure: LtSptSRoETbYY/rMcIozsriMX8cFcjchRlaBpon8GkwCwPnuIgdvm2G/AUuyAqg5nHQD0CudWypcwzNfO9xxxKJ50xr438IC1FPo3Q2Cfkfb9I4yGE19pON1dAlr9oDU7lAmETUpRXcV2Bv5T6BjWzGY4mCdZw7YeIIF0kMzUQWPHTpu4nhz30m+AheQxqqgp6LvPCWp2rXM+LFYn29T320Qlv2es8TSMTmu0DLtFNx9WMA4iMbrFJSi8ne8CLtNmgurfG+ar5sQzbQTVHNxKQU4bZqUzDf0pR4ZMOuxtYUGAuwCtF87ayWf7powjAOR1DtDThBVdPZpPJFIDKa8+Oab5+TfyUZpVvVLC86qOulK/XheIKuFQJK+EJKPMxEPdft/NZlOGvBpfHuV1K7PGFhDjyaIVmD8PLTq+dnLvbqhRNpZD9vMVdWp+5zPwDIigVs+pKG5nOBJQ16mmpkqvFC2nhK+/mYJVvvA8iraCQsqhKC1ts28myBxHv2e/ZVIE8Hkg1YL1804Go/iaYVERfJbZd/vD5Ylm7UXU1+L9blKznS6uWz+LbKaB7oToMGxag7TF+4EQq4X4wKeoVyceoyQvvQL/R+m6bPyTmPD2qsp/DNdjGRg0w8EecEoh+fZ27cw0pEXKZLyGZbtL2VJYXPSmOA70m81Z+fuE42qbOU=
  app: todo-workshop-wvu
  on:
    repo: bhorn1/wvu-workshop
    branch: front-end
